services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - myapp
    depends_on:
      - frontend
      - backend

  frontend:
    image: frontend
    stdin_open: true
    tty: true
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - ./services/frontend:/app
    working_dir: /app
    networks:
      - myapp


  backend:
    image: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    volumes:
      - ./services/backend:/app
    environment:
      PGSERVICEFILE: /run/secrets/pg_service
      CELERY_BROKER_URL_FILE: /run/secrets/celery_broker_url
      CELERY_RESULT_BACKEND_FILE: /run/secrets/celery_result_backend
    secrets:
      - pg_service
      - pgpass
      - celery_broker_url
      - celery_result_backend
    working_dir: /app
    command: uv run python manage.py runserver 0.0.0.0:8000
    networks:
      - myapp
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: test-db
    secrets:
      - postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    environment:
      RABBITMQ_CONFIG_FILE: /run/secrets/rabbitmq.conf
      RABBITMQ_NODENAME: rabbit@rabbitmq
    secrets:
      - rabbitmq.conf
    networks:
      - myapp

networks:
  myapp:
volumes:
  db_data:
    name: db_data
  
  rabbitmq_data:
    name: rabbitmq_data

secrets:
  postgres_password:
    file: ./secrets/postgres_password

  celery_broker_url:
    environment: CELERY_BROKER_URL

  celery_result_backend:
    environment: CELERY_RESULT_BACKEND

  rabbitmq.conf:
    file: ./secrets/rabbitmq.conf
  
  pg_service:
    file: ./secrets/.pg_service.conf

  pgpass:
    file: ./secrets/.pgpass

  