[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "celery[librabbitmq,sqlalchemy]>=5.5.1",
    "channels[daphne]>=4.2.2",
    "django>=5.2",
    "psycopg[binary]>=3.2.6",
    "sqlalchemy>=2.0.40",
    "tzdata>=2025.2",
]