# Generated by Django 5.2 on 2025-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonPress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('last_pressed', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
